### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by goddice** [pytorch-labs/torchft#30]
Firstly, I was trying to run the train.py in the README, but it reminded me that ```min_replica_size``` was missing for ```Manager```. I fixed that but it keeps showing ```Address already in use``` error. Even I got the error with the following command. How should I fix it? Thanks~

$ RUST_BACKTRACE=1 torchft_lighthouse --min_replicas 1 --quorum_tick_ms 100 --join_timeout_ms 1000
Traceback (most recent call last):
  File "/home/tiger/.local/bin/torchft_lighthouse", line 8, in <module>
    sys.exit(lighthouse_main())
             ^^^^^^^^^^^^^^^^^
RuntimeError: Address already in use (os error 98)

**Comment by fegin** [comment]
You can try passing  `--bind "0.0.0.0:SOME_PORT_NUMBER"`. Change SOME_PORT_NUMBER to some number other than `29510`, which is the default one.

**Comment by d4l3k** [comment]
@goddice let me know if you run into any other issues -- also happy to chat/invite you to the PyTorch slack if you want to discuss things more. This repo is still early on so any feedback is welcome :)

**Comment by d4l3k** [comment]
Closing this issue for now -- feel free to reopen it if that workaround doesn't help

**Comment by goddice** [comment]
> @goddice let me know if you run into any other issues -- also happy to chat/invite you to the PyTorch slack if you want to discuss things more. This repo is still early on so any feedback is welcome :)

The issue is gone. I found this repo might be useful for my training task. Thanks.
